### ISSUE TITLE
Create Header & Dummy Card (US 1)

### ISSUE THREAD

**Issue by muhammed-basaran** [muhammed-basaran/capstone-project#1]
## Value Proposition

**As a** user

**I need** some cards with content( name, price, date)

**to be able to** know what kind of shoes will be offered

## Description
Scribble / design or text

<img width="174" alt="Bildschirmfoto 2022-12-12 um 10 05 36" src="https://user-images.githubusercontent.com/115261964/207005285-e5b8cb76-c1db-4948-a626-12ddcea5e58a.png">

## Acceptance Criteria

- [x] all cards have the content: name, price , img, release date 
- [x] at least 5 cards should be created 
- [x] after 2-3 cards, the overflow is scrollable

## Tasks

(for developers team)

- [x] work on branch
- [x] e.g. Components, Storybook, testing
- [x] create Header with title
- [x] create 5-6 dummy cards with content: name, price, img  
- [x] give some layout for body and cards

**Comment by ufelgen** [comment]
Hey Moe, ich finde das für den Einstieg gut strukturiert und durchdacht. Hätte eine klitzekleine Anmerkung zur value proposition: willst du spezifizieren, was der Content ist? "I need some cards with content" kann ja (fast) alles bedeuten :) Uuuuuund ich hab gerade noch einen Einfall gehabt. "pick my sneakers" ist deine Überschrift - was hältst du von "Sneak Pick" (in Anlehnung an Sneak Peek 🙈)

**Comment by muhammed-basaran** [comment]
ob dus glaubst oder nicht genau den Namen hatte ich mir ausgesucht, aber leider bereits an eine israelische Schuhfirma vergeben....

**Comment by ufelgen** [comment]
> ob dus glaubst oder nicht genau den Namen hatte ich mir ausgesucht, aber leider bereits an eine israelische Schuhfirma vergeben....

neiiiiiiin 😭 doof. kannst du die Firma kaufen?

Angebot ist raus !!
