### ISSUE TITLE
add slider for pictures

### ISSUE THREAD

**Issue by muhammed-basaran** [muhammed-basaran/capstone-project#12]
## Value Proposition

**As a** user 
**I want to** see more picture of a product
**so that**  I can change between some pictures
​

## Description
<img width="344" alt="Bildschirmfoto 2022-12-19 um 16 36 34" src="https://user-images.githubusercontent.com/115261964/208462893-b7a70f75-50ec-4200-a409-eebeee152618.png">

...
​

## Acceptance Criteria

- [x] if you click on the blue circle, the picture changes to ne next one
- [x] the pictures are in a frame with slider function
- 
      ​

## Tasks

- [x] add more pictures
- [x] add logic for mapping the pictures in the frame 
- [x] add logic for sliding 
- [x] use branch 
      ​

## Complexity

...

**Comment by esrefbozkurt** [comment]
for changing a picture i would recommend something like the picture below with arrows on the left and right. maybe it is a bit hard to aim for the small blue circle. Besides that it looks very nice, good job!

![IMG_3085](https://user-images.githubusercontent.com/113592929/208467125-8a5f377c-76bf-4b7a-9bd9-13208b053148.PNG)
