### ISSUE TITLE
add counter for the fav Icon

### ISSUE THREAD

**Issue by muhammed-basaran** [muhammed-basaran/capstone-project#13]
## Value Proposition

**As a** user
**I want to** see the popularity  of the product
**so that**  I can see how much people give a like
​

## Description

...
<img width="357" alt="Bildschirmfoto 2022-12-19 um 16 46 05" src="https://user-images.githubusercontent.com/115261964/208464863-c3d13a2f-975f-4d21-affa-a946af8ca8af.png">

​

## Acceptance Criteria

- [x] the fav icon on the overviewpage has a counter 
- [x] users liked icon has the red icon 
      ​

## Tasks

- [x] create a counter logic for the fav icon 
- [x] work at branch 
      ​

## Complexity

...

**Comment by esrefbozkurt** [comment]
Nice Idea! 
For my understanding : If you are logged in, you are in the taste to see the fav icon in color ?
For the first Task i would add "and display the counter next to the fav icon". Something like that. Good work!
