### ISSUE TITLE
Add footer with navbar 

### ISSUE THREAD

**Issue by muhammed-basaran** [muhammed-basaran/capstone-project#15]
## Value Proposition

**As a** user  
**I want to** have a favorites page 
**so that** I can find liked shoes easier and faster
​

## Description
<img width="442" alt="Bildschirmfoto 2023-01-03 um 18 57 36" src="https://user-images.githubusercontent.com/115261964/210414616-0f21ba29-a58c-4dde-9229-81f6f96d8670.png">

...
​

## Acceptance Criteria

- [x] click on empty fire icon routes to the Favorites page 
- [x] on the Favorites pages the fire icon is filled 
- [x] click on empty home icon routes to the Homepage
- [x] on the Homepage the home icon is filled 
      ​

## Tasks

- [x] work on branch
- [x] add a footer
- [x] add home and fire icon to the footer 
- [x] create fav page with footer 
- [x] add routing to the fav page 
      ​

## Complexity

...
