### ISSUE TITLE
render liked cards on the fav page 

### ISSUE THREAD

**Issue by muhammed-basaran** [muhammed-basaran/capstone-project#16]
## Value Proposition

**As a** user 
**I want to** see the liked shoes on my fav page 
**so that** i can find them faster 
​

## Description

...
<img width="657" alt="Bildschirmfoto 2023-01-03 um 19 09 23" src="https://user-images.githubusercontent.com/115261964/210415971-611bb058-e1f6-4894-b970-baaf894a4055.png">

​

## Acceptance Criteria

- [x] liked shoes have a red fire icon 
- [x] only liked shoes are listed on the fav page 
- [x] disliked shoes get deleted from the fav page 
      ​

## Tasks

- [x] work on branch 
- [x] create a new array on fav page with only liked shoes 

      ​

## Complexity

...
