### ISSUE TITLE
filtering for the homepage 

### ISSUE THREAD

**Issue by muhammed-basaran** [muhammed-basaran/capstone-project#17]
## Value Proposition

**As a** user   
**I want to** be able to filter the shoes 
**so that** i see only my favorite brands 
​

## Description

...
<img width="591" alt="Bildschirmfoto 2023-01-03 um 19 28 22" src="https://user-images.githubusercontent.com/115261964/210418926-135f7bd0-10ae-4fb2-b93e-8557d5a43c34.png">

​

## Acceptance Criteria

- [x] you can see only the shoes with the selected brand 

      ​

## Tasks

- [x] work on branch
- [x] add a filter function on the brand icons 
      ​

## Complexity

...
