### ISSUE TITLE
Create overviewCArd (US 2)

### ISSUE THREAD

**Issue by muhammed-basaran** [muhammed-basaran/capstone-project#2]
## Value Proposition

**As a** user

**I need** more informations about the products (color, stories)

**to be able to** to get more details about the product 

## Description
Scribble / design or text

<img width="333" alt="Bildschirmfoto 2022-12-12 um 10 13 19" src="https://user-images.githubusercontent.com/115261964/207006850-4155222e-1ddd-4ecb-9baa-2354944dc6fc.png">

## Acceptance Criteria

- [x] create bigger card with more details about the product
- [x] bigger img, more img
- [x] only 1 card is shown on the screen 
- [x] one new card for each created card
- [x] on click at the card you can toggle between both views

## Tasks

(for developers team)

- [x] work on branch
- [x] e.g. Components, Storybook, testing
- [x] create Header with title
- [x] create 5-6 dummycards
- [x] give some layout for body and cards 
- [x] onClick event/routing NextJs

**Comment by ufelgen** [comment]
"on click you can toggle between both views" wo klickt man? kannst du das in deinem Design noch hinzufügen? :)

**Comment by muhammed-basaran** [comment]
> "on click you can toggle between both views" wo klickt man? kannst du das in deinem Design noch hinzufügen? :)

merci, wusste nicht wie ich es beschreiben soll, auf jeden Fall auf die card selbst

**Comment by julialoeschel** [comment]
:octocat:  lgtm

passend zur ersten schlage ich auch hier wieder vor, die Daten vorher zu gererieren und den ganzen Code nicht hart zu coden (Sprat Zeit).

ansonsten sehr gut 👍
