### ISSUE TITLE
add DataBase mongoDB 

### ISSUE THREAD

**Issue by muhammed-basaran** [muhammed-basaran/capstone-project#23]
## Value Proposition

**As a** developer
**I want to** save data in a database
**so that** i am able to store it and edit it more comfortable
​

## Description

I fully integrate a mongoDB to replace my Sneaker Array saved in the data lib.
​

## Acceptance Criteria

- [x] ...
      ​

## Tasks

- [x] setup a new mongoDB in Atlas
- [x]  add a db folder to my project including the data model and a dbConnect.js
- [x]  replace all the refers in the code from the old "shoes.js" file to the new database
- [x] setup the Atlas connection to the cloud
      ​

## Complexity

...
