### ISSUE TITLE
dynamic Code/routes US3

### ISSUE THREAD

**Issue by muhammed-basaran** [muhammed-basaran/capstone-project#3]
## Value Proposition

**As a** user

**I need** more informations about the products (color, stories)

**to be able to** to get more details about the product 

## Description
Scribble / design or text

<img width="292" alt="Bildschirmfoto 2022-12-12 um 10 27 15" src="https://user-images.githubusercontent.com/115261964/207009764-cb7a733d-d409-4cda-9d3d-d09884882cc5.png">

## Acceptance Criteria

- [x] array with at least 20 - 30 Objects
- [x] rendering cards with dynamic code
- [x] routing also with dynamic code on Click 

## Tasks

(for developers team)

- [x] work on branch
- [x] use dynamic code for rendering card with array
- [ ] change the routing to dynamic over id

**Comment by altanguellue** [comment]
Gute, short Userstory. Auf den Punkt gebracht. Eine Frage noch: Sollen die Objekte aus dem Array als card components untereinander aufgelistet werden?

**Comment by muhammed-basaran** [comment]
> Gute, short Userstory. Auf den Punkt gebracht. Eine Frage noch: Sollen die Objekte aus dem Array als card components untereinander aufgelistet werden?

danke :) die Objekte aus dem Array sollen die bisherigen Dummies ersetzen
