### ISSUE TITLE
Add Button und link reseller websites (US4)

### ISSUE THREAD

**Issue by muhammed-basaran** [muhammed-basaran/capstone-project#4]
## Value Proposition

**As a** user

**I need** details where i can get this shoe

**to be able to** to change to the sellers website 

## Description
Scribble / design or text

<img width="330" alt="Bildschirmfoto 2022-12-12 um 15 25 26" src="https://user-images.githubusercontent.com/115261964/207069965-970c9b4d-74a4-40c5-a056-0819dc8b07d2.png">

## Acceptance Criteria

- [x] BUY button for changing to the list of reseller names 
- [x] click on the shop name for opening the website 
- [x] BACK button to change to the overview card

## Tasks

(for developers team)

- [x] work on branch
- [x] add Button Component
- [x] create BUY button on the bottom of the end 
- [x] create BACK button 
- [x] onClick event on the name of the shop 
- [x] create new card with link to resellers/sellers Homepage
- [x] give some layout as flexbox and style for cards

**Comment by marvinRoellecke** [comment]
Moe, good work!

>  give some layout and style for cards

Maybe you can provide more detailed information. Like how you want to do the layout (e.g. grid oder flexbox)
