### ISSUE TITLE
Add fav/like icon-button (US5)

### ISSUE THREAD

**Issue by muhammed-basaran** [muhammed-basaran/capstone-project#5]
## Value Proposition

**As a** user

**I need**possibility to like my favourite shoes

**to be able to** be up to date for the release

## Description
Scribble / design or text

![image](https://user-images.githubusercontent.com/115261964/207082017-a95a2627-7fb6-429b-bd76-276233d0d2ae.png)

## Acceptance Criteria

- [x] black fire icon at card gets red if the user clicks/likes the the icon 

## Tasks

(for developers team)

- [x] add black fire icon
- [x] add onClick event on icon so that the icon can toggle by clicking between red and black

**Comment by ufelgen** [comment]
Hey Moe, mega coole Idee mit dem 🔥 ! Du willst das togglen oder? sodass das rote Feuer wieder schwarz wird, wenn du drauf klickst? Das würde ich noch beschreiben :) ansonsten prima, sehr simpel und gut umsetzbar. Ich nehme an, eine Favoriten-Seite, wo nur die markierten Karten angezeigt werden, wird dann in einem nächsten Schritt gerendert, das finde ich okay, das zu trennen. 
PS: die Formulierung deiner value proposition finde ich super!

**Comment by muhammed-basaran** [comment]
> Hey Moe, mega coole Idee mit dem 🔥 ! Du willst das togglen oder? sodass das rote Feuer wieder schwarz wird, wenn du drauf klickst? Das würde ich noch beschreiben :) ansonsten prima, sehr simpel und gut umsetzbar. Ich nehme an, eine Favoriten-Seite, wo nur die markierten Karten angezeigt werden, wird dann in einem nächsten Schritt gerendert, das finde ich okay, das zu trennen. PS: die Formulierung deiner value proposition finde ich super!

Merci für dein Review, habe ich so übernommen :) Und danke für die props:)
